namespace ConvertAPP.Models
{
    public class Cliente
    {
        public int codCli { get; set; }
        public int codLoj { get; set; }
        public string nomCli { get; set; }
        public DateTime? datNas { get; set; }
        public string cliBlo { get; set; }
        public string creLib { get; set; }
        public string fisJur { get; set; }
        public int codTp1 { get; set; }
        public int codTp2 { get; set; } 
        public string cpfCli { get; set; }
        public string ideCli { get; set; }
        public DateTime datIde { get; set; }
        public string uf_Ide { get; set; }
        public string orgIde { get; set; }  
        public string carTra { get; set; }
        public string nmInss { get; set; }
        public string estCiv { get; set; }
        public string sexCli { get; set; }  
        public string natCli { get; set; }
        public string nomPai { get; set; }
        public string nomMae { get; set; }
        public string endRes { get; set; }
        public int nm_EndRes { get; set; }
        public string baiRes { get; set; }
        public string cidRes { get; set; }
        public string estRes { get; set; }
        public string cepRes { get; set; }
        public string fonRes { get; set; }
        public string celula { get; set; }
        public string infAdc { get; set; }
        public string eMail { get; set; }
        public string tipCas { get; set; }
        public string resDes { get; set; }
        public float valAlu { get; set; }
        public string endEnt { get; set; }
        public int nm_endEnt { get; set; }
        public string baiEnt { get; set; }
        public string cidEnt { get; set; }
        public string estEnt { get; set; }
        public string cepEnt { get; set; }
        public string fonEnt { get; set; }
        public string nomEmp { get; set; }
        public string cnpEmp { get; set; }
        public string endEmp { get; set; }
        public int nm_endEmp { get; set; }
        public string baiEmp { get; set; }
        public string cidEmp { get; set; }
        public string estEmp { get; set; }
        public string cepEmp { get; set; }
        public string fonEmp { get; set; }
        public string ramEmp { get; set; }
        public DateTime admEmp { get; set; }
        public string carEmp { get; set; }
        public float salEmp { get; set; }   
        public string nomCjg { get; set; }
        public DateTime datNasCj { get; set; }
        public string celulaCj { get; set; }
        public string eMailCj { get; set; }
        public string cpfCliCj { get; set; }
        public string ideCliCj { get; set; }
        public string natCliCj { get; set; }
        public string nomPaiCj { get; set; }
        public string nomMaeCj { get; set; }
        public string nomEmpCj { get; set; }
        public int nm_endEmpCj { get; set; }
        public string cnpEmpCj { get; set; }
        public string endEmpCj { get; set; }
        public string baiEmpCj { get; set; }
        public string cidEmpCj { get; set; }
        public string estEmpCj { get; set; }
        public string cepEmpCj { get; set; }
        public string fonEmpCj { get; set; }
        public string ramEmpCj { get; set; }
        public DateTime admEmpCj { get; set; }
        public string carEmpCj { get; set; }
        public float salEmpCj { get; set; } 
        public string refPes1 { get; set; }
        public string fonRefP1 { get; set; }
        public string prtRefP1 { get; set; }
        public string refPes2 { get; set; }
        public string fonRefP2 { get; set; }
        public string prtRefP2 { get; set; }
        public string refCom1 { get; set; } 
        public string fonRefC1 { get; set; }
        public string refCom2 { get; set; }
        public string fonRefC2 { get; set; }
        public float limCre { get; set; }
        public string matCvn { get; set; }
        public string dadBan { get; set; }
        public DateTime cliDes { get; set; }
        public int lojAlt { get; set; }
        public int lojLog { get; set; }
        public int vctFat { get; set; }
        public int trmLog { get; set; }
        public int usrLog { get; set; }
        public DateTime ultAlt { get; set; }
        public int on_Off { get; set; }
        public DateTime datExp { get; set; }
        public int lojExp { get; set; }
        public int codFrq { get; set; }
        public string codOld { get; set; }
        public int codFun { get; set; }
    }
}
